"""Model adapters and the ModelBus. Provider-specific code, behind a core protocol."""

from tesserix_adk.core.capabilities import Capability, ModelCapabilities, ModelRef, ModelSpec
from tesserix_adk.core.errors import (
    CapabilityError,
    ContextWindowExceededError,
    ModelResponseError,
    StreamInterruptedError,
    ToolArgumentValidationError,
)
from tesserix_adk.core.protocols import ModelProvider, SecretProvider
from tesserix_adk.core.provider import ModelRequest, ModelResponse, StopReason, ToolDeclaration
from tesserix_adk.core.streaming import (
    ReasoningDelta,
    StreamAccumulator,
    StreamEnd,
    StreamEvent,
    TextDelta,
    ToolCallDelta,
    UsageDelta,
)
from tesserix_adk.models.cache import (
    Cacheability,
    CacheEntry,
    CacheKey,
    CacheMetrics,
    CacheOutcome,
    CachePolicy,
    CacheStatus,
    CacheStore,
    CachingProvider,
    MemoryCacheStore,
    MemorySemanticIndex,
    SemanticConfig,
    SemanticIndex,
    not_cacheable,
)
from tesserix_adk.models.catalogue import (
    CATALOGUE_VERSION,
    ModelCard,
    Pricing,
    known_models,
    model_card,
    priced,
)
from tesserix_adk.models.credentials import Credential, EnvironmentSecrets
from tesserix_adk.models.embeddings import (
    BatchConfig,
    BatchingEmbedder,
    EmbeddingLimits,
    EmbeddingMetrics,
    EmbeddingProvider,
    Vector,
)
from tesserix_adk.models.pool import ClientKey, ClientPool, PoolConfig, PoolMetrics

__all__ = [
    "CATALOGUE_VERSION",
    "BatchConfig",
    "BatchingEmbedder",
    "CacheEntry",
    "CacheKey",
    "CacheMetrics",
    "CacheOutcome",
    "CachePolicy",
    "CacheStatus",
    "CacheStore",
    "Cacheability",
    "CachingProvider",
    "Capability",
    "CapabilityError",
    "ClientKey",
    "ClientPool",
    "ContextWindowExceededError",
    "Credential",
    "EmbeddingLimits",
    "EmbeddingMetrics",
    "EmbeddingProvider",
    "EnvironmentSecrets",
    "MemoryCacheStore",
    "MemorySemanticIndex",
    "ModelCapabilities",
    "ModelCard",
    "ModelProvider",
    "ModelRef",
    "ModelRequest",
    "ModelResponse",
    "ModelResponseError",
    "ModelSpec",
    "PoolConfig",
    "PoolMetrics",
    "Pricing",
    "ReasoningDelta",
    "SecretProvider",
    "SemanticConfig",
    "SemanticIndex",
    "StopReason",
    "StreamAccumulator",
    "StreamEnd",
    "StreamEvent",
    "StreamInterruptedError",
    "TextDelta",
    "ToolArgumentValidationError",
    "ToolCallDelta",
    "ToolDeclaration",
    "UsageDelta",
    "Vector",
    "known_models",
    "model_card",
    "not_cacheable",
    "priced",
]
