"""Model adapters and the ModelBus. Provider-specific code, behind a core protocol."""

from tesserix_adk.core.capabilities import Capability, ModelCapabilities, ModelRef, ModelSpec
from tesserix_adk.core.errors import (
    CapabilityError,
    ContextWindowExceededError,
    ModelResponseError,
    StreamInterruptedError,
    ToolArgumentValidationError,
)
from tesserix_adk.core.protocols import ModelProvider, SecretProvider
from tesserix_adk.core.provider import ModelRequest, ModelResponse, StopReason, ToolDeclaration
from tesserix_adk.core.streaming import (
    ReasoningDelta,
    StreamAccumulator,
    StreamEnd,
    StreamEvent,
    TextDelta,
    ToolCallDelta,
    UsageDelta,
)
from tesserix_adk.models.cache import (
    Cacheability,
    CacheEntry,
    CacheKey,
    CacheMetrics,
    CacheOutcome,
    CachePolicy,
    CacheStatus,
    CacheStore,
    CachingProvider,
    MemoryCacheStore,
    MemorySemanticIndex,
    SemanticConfig,
    SemanticIndex,
    not_cacheable,
)
from tesserix_adk.models.catalogue import (
    CATALOGUE_VERSION,
    ModelCard,
    Pricing,
    known_models,
    model_card,
    priced,
)
from tesserix_adk.models.credentials import Credential, EnvironmentSecrets
from tesserix_adk.models.embeddings import (
    BatchConfig,
    BatchingEmbedder,
    EmbeddingLimits,
    EmbeddingMetrics,
    EmbeddingProvider,
    Vector,
)
from tesserix_adk.models.onnx import (
    ONNX_MODELS,
    Device,
    Encoded,
    OnnxCrossEncoder,
    OnnxEmbeddings,
    OnnxMetrics,
    OnnxModel,
    OnnxSession,
    Throughput,
    Tokenizing,
    load_session,
    onnx_model,
    verify_artefact,
)
from tesserix_adk.models.pool import ClientKey, ClientPool, PoolConfig, PoolMetrics
from tesserix_adk.models.shaping import (
    TOOL_ERROR,
    Effort,
    Shaped,
    Shaping,
    TurnKind,
    classify,
    errored,
    provider_effort,
)

__all__ = [
    "CATALOGUE_VERSION",
    "ONNX_MODELS",
    "TOOL_ERROR",
    "BatchConfig",
    "BatchingEmbedder",
    "CacheEntry",
    "CacheKey",
    "CacheMetrics",
    "CacheOutcome",
    "CachePolicy",
    "CacheStatus",
    "CacheStore",
    "Cacheability",
    "CachingProvider",
    "Capability",
    "CapabilityError",
    "ClientKey",
    "ClientPool",
    "ContextWindowExceededError",
    "Credential",
    "Device",
    "Effort",
    "EmbeddingLimits",
    "EmbeddingMetrics",
    "EmbeddingProvider",
    "Encoded",
    "EnvironmentSecrets",
    "MemoryCacheStore",
    "MemorySemanticIndex",
    "ModelCapabilities",
    "ModelCard",
    "ModelProvider",
    "ModelRef",
    "ModelRequest",
    "ModelResponse",
    "ModelResponseError",
    "ModelSpec",
    "OnnxCrossEncoder",
    "OnnxEmbeddings",
    "OnnxMetrics",
    "OnnxModel",
    "OnnxSession",
    "PoolConfig",
    "PoolMetrics",
    "Pricing",
    "ReasoningDelta",
    "SecretProvider",
    "SemanticConfig",
    "SemanticIndex",
    "Shaped",
    "Shaping",
    "StopReason",
    "StreamAccumulator",
    "StreamEnd",
    "StreamEvent",
    "StreamInterruptedError",
    "TextDelta",
    "Throughput",
    "Tokenizing",
    "ToolArgumentValidationError",
    "ToolCallDelta",
    "ToolDeclaration",
    "TurnKind",
    "UsageDelta",
    "Vector",
    "classify",
    "errored",
    "known_models",
    "load_session",
    "model_card",
    "not_cacheable",
    "onnx_model",
    "priced",
    "provider_effort",
    "verify_artefact",
]
