"""Generate checked API-reference pages from the declared public surface."""

from __future__ import annotations

import argparse
import ast
import difflib
import importlib
import inspect
import json
import pkgutil
import re
import sys
import textwrap
from pathlib import Path, PurePosixPath
from types import FunctionType, ModuleType
from typing import TYPE_CHECKING, cast

import tesserix_adk.experimental
from tesserix_adk.core.deprecation import Deprecation, deprecations
from tesserix_adk.core.errors import AdkError
from tools.api_surface import collect_surface, public_modules, third_party_re_exports

if TYPE_CHECKING:
    from collections.abc import Mapping, Sequence

ROOT = Path(__file__).resolve().parents[1]
REFERENCE = ROOT / "docs" / "reference"
STABILITY = ROOT / "docs" / "stability.md"
RECIPES = ROOT / "docs" / "cookbook" / "symbols.json"
GENERATED = "<!-- generated by tools.api_reference; do not edit -->\n"

_MATRIX_ROW = re.compile(r"^\| `([a-z0-9_]+)` \| `([a-z]+)` \|", re.MULTILINE)
_ENTRY = re.compile(r"^\s{4}([*]{0,2}[A-Za-z_]\w*)\s*(?:\([^)]*\))?:")
_ERROR_ENTRY = re.compile(r"^\s{4}([A-Za-z_]\w*(?:\.[A-Za-z_]\w*)*)\s*:")


class ReferenceError(Exception):  # noqa: A001 — established generator-specific public error
    """Raised when public docstrings cannot support an accurate reference."""

    def __init__(self, issues: tuple[str, ...]) -> None:
        self.issues = issues
        super().__init__("API reference validation failed:\n- " + "\n- ".join(issues))


class _RaiseVisitor(ast.NodeVisitor):
    """Collect raises in one callable body without entering nested callables."""

    def __init__(self) -> None:
        self.expressions: list[ast.expr] = []

    def visit_Raise(self, node: ast.Raise) -> None:
        if node.exc is not None:
            self.expressions.append(node.exc)

    def visit_FunctionDef(self, _node: ast.FunctionDef) -> None:
        return

    def visit_AsyncFunctionDef(self, _node: ast.AsyncFunctionDef) -> None:
        return

    def visit_ClassDef(self, _node: ast.ClassDef) -> None:
        return

    def visit_Lambda(self, _node: ast.Lambda) -> None:
        return


def _objects(
    modules: Sequence[ModuleType] | None = None,
) -> tuple[dict[str, str], dict[str, object], tuple[ModuleType, ...]]:
    selected = tuple(public_modules() if modules is None else modules)
    surface = collect_surface(selected)
    objects: dict[str, object] = {}
    for module in selected:
        for name in getattr(module, "__all__", ()):
            value = getattr(module, name, None)
            key = f"{module.__name__}.{name}"
            if value is not None and key in surface:
                objects[key] = value
    return surface, objects, selected


def _section(docstring: str, title: str) -> tuple[str, ...]:
    lines = inspect.cleandoc(docstring).splitlines()
    marker = f"{title}:"
    try:
        start = lines.index(marker) + 1
    except ValueError:
        return ()
    section: list[str] = []
    for line in lines[start:]:
        if line and not line[0].isspace():
            break
        section.append(line)
    return tuple(section)


def _documented_parameters(docstring: str) -> set[str]:
    documented: set[str] = set()
    for line in _section(docstring, "Args"):
        match = _ENTRY.match(line)
        if match is not None:
            documented.add(match.group(1).lstrip("*"))
    return documented


def _documented_errors(docstring: str) -> set[str]:
    documented: set[str] = set()
    for line in _section(docstring, "Raises"):
        match = _ERROR_ENTRY.match(line)
        if match is not None:
            documented.add(match.group(1).rsplit(".", 1)[-1])
    return documented


def _function_node(function: FunctionType) -> ast.FunctionDef | ast.AsyncFunctionDef | None:
    try:
        source = inspect.getsource(function)
    except (OSError, TypeError):
        return None
    try:
        tree = ast.parse(textwrap.dedent(source))
    except SyntaxError:
        return None
    candidates = [
        node for node in tree.body if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))
    ]
    return next((node for node in candidates if node.name == function.__name__), None)


def _resolved(expression: ast.expr, namespace: Mapping[str, object]) -> object | None:
    if isinstance(expression, ast.Call):
        return _resolved(expression.func, namespace)
    if isinstance(expression, ast.Name):
        return namespace.get(expression.id)
    if isinstance(expression, ast.Attribute):
        parent = _resolved(expression.value, namespace)
        return getattr(parent, expression.attr, None) if parent is not None else None
    return None


def _direct_typed_errors(value: object) -> tuple[type[AdkError], ...]:
    if not isinstance(value, FunctionType):
        return ()
    target = inspect.unwrap(value)
    if not isinstance(target, FunctionType):
        return ()
    node = _function_node(target)
    if node is None:
        return ()
    visitor = _RaiseVisitor()
    for statement in node.body:
        visitor.visit(statement)
    errors: set[type[AdkError]] = set()
    for expression in visitor.expressions:
        resolved = _resolved(expression, target.__globals__)
        if not isinstance(resolved, type):
            continue
        try:
            typed = issubclass(resolved, AdkError)
        except TypeError:
            typed = False
        if typed:
            errors.add(resolved)
    return tuple(sorted(errors, key=lambda error: error.__name__))


def _error_is_documented(error: type[AdkError], documented: set[str]) -> bool:
    return any(base.__name__ in documented for base in error.__mro__ if base is not Exception)


def validate(modules: Sequence[ModuleType] | None = None) -> None:
    """Validate callable docstrings against signatures and directly raised ADK errors.

    Args:
        modules: Modules to validate. The declared public package surface is the default.

    Raises:
        ReferenceError: If a callable lacks documentation, names a stale parameter, or
            omits a directly raised typed error.
    """
    _, objects, _ = _objects(modules)
    issues: list[str] = []
    seen: set[int] = set()
    for name, value in sorted(objects.items()):
        if id(value) in seen or not (inspect.isfunction(value) or inspect.isclass(value)):
            continue
        seen.add(id(value))
        docstring = inspect.getdoc(value)
        if not docstring:
            issues.append(f"{name} has no public docstring")
            continue
        if inspect.isfunction(value):
            try:
                parameters = set(inspect.signature(value).parameters)
            except (TypeError, ValueError):
                parameters = set()
            stale = sorted(_documented_parameters(docstring) - parameters)
            if stale:
                issues.append(
                    f"{name} documents parameters not in its signature: {', '.join(stale)}"
                )
            documented_errors = _documented_errors(docstring)
            for error in _direct_typed_errors(value):
                if not _error_is_documented(error, documented_errors):
                    issues.append(
                        f"{name} directly raises {error.__name__} but omits it from Raises"
                    )
    if issues:
        raise ReferenceError(tuple(issues))


def _stability_matrix() -> dict[str, str]:
    return dict(_MATRIX_ROW.findall(STABILITY.read_text(encoding="utf-8")))


def _stability(name: str, value: object, matrix: Mapping[str, str]) -> str:
    parts = name.split(".")
    if len(parts) > 2 and parts[1] in matrix:
        return matrix[parts[1]]
    origin = getattr(value, "__module__", "")
    origin_parts = origin.split(".")
    if len(origin_parts) > 1 and origin_parts[1] in matrix:
        return matrix[origin_parts[1]]
    return "beta"


def _recipe_contract() -> tuple[dict[str, str], dict[str, dict[str, str]]]:
    document = cast("dict[str, object]", json.loads(RECIPES.read_text(encoding="utf-8")))
    raw_symbols = cast("dict[str, object]", document.get("symbols", {}))
    raw_recipes = cast("dict[str, object]", document.get("recipes", {}))
    symbols = {name: str(identifier) for name, identifier in raw_symbols.items()}
    recipes: dict[str, dict[str, str]] = {}
    for identifier, raw in raw_recipes.items():
        if isinstance(raw, dict):
            recipes[identifier] = {str(key): str(value) for key, value in raw.items()}
    return symbols, recipes


def _summary(value: object) -> str:
    docstring = inspect.getdoc(value)
    if not docstring:
        return "Exported value."
    return " ".join(docstring.split("\n\n", 1)[0].splitlines())


def _recipe_line(
    name: str, symbols: Mapping[str, str], recipes: Mapping[str, dict[str, str]]
) -> str:
    identifier = symbols[name]
    recipe = recipes[identifier]
    page = PurePosixPath(recipe["page"]).relative_to("docs")
    link = PurePosixPath("..") / page
    extra = recipe.get("extra")
    install = f" Install `tesserix-adk[{extra}]`." if extra else ""
    return (
        f"**Runnable recipe:** [{recipe['recipe']}]({link.as_posix()}) — {recipe['rule']}.{install}"
    )


def _deprecation_for(name: str, records: Mapping[str, Deprecation]) -> str | None:
    record = records.get(name)
    if record is None:
        return None
    return (
        f'!!! warning "Deprecated since {record.since}; removal {record.removal}"\n'
        f"    Use `{record.alternative}`. {record.reason or ''}".rstrip()
    )


def _symbol_block(
    name: str,
    description: str,
    value: object,
    *,
    level: str,
    symbols: Mapping[str, str],
    recipes: Mapping[str, dict[str, str]],
    third_party: bool,
    records: Mapping[str, Deprecation],
) -> str:
    errors = sorted(_documented_errors(inspect.getdoc(value) or ""))
    error_text = ", ".join(f"`{error}`" for error in errors) if errors else "None declared."
    badges = [f"**Stability:** `{level}`"]
    if getattr(value, "_is_protocol", False):
        badges.append("**Kind:** `Protocol`")
    if third_party:
        badges.append("**Origin:** upstream re-export")
    parts = [
        f"## `{name}`",
        " · ".join(badges),
        _summary(value),
        f"```python\n{description}\n```",
        f"**Typed errors:** {error_text}",
        _recipe_line(name, symbols, recipes),
    ]
    warning = _deprecation_for(name, records)
    if warning is not None:
        parts.insert(2, warning)
    return "\n\n".join(parts) + "\n"


def _canonical_names(objects: Mapping[str, object]) -> dict[int, str]:
    choices: dict[int, list[str]] = {}
    for name, value in objects.items():
        choices.setdefault(id(value), []).append(name)

    canonical: dict[int, str] = {}
    for identifier, names in choices.items():
        value = objects[names[0]]
        origin = getattr(value, "__module__", "")
        canonical[identifier] = min(
            names,
            key=lambda name: (name.rsplit(".", 1)[0] != origin, name.count("."), len(name), name),
        )
    return canonical


def _protocol_page(objects: Mapping[str, object]) -> str:
    canonical = _canonical_names(objects)
    classes = {
        canonical[id(value)]: value
        for value in objects.values()
        if inspect.isclass(value) and id(value) in canonical
    }
    protocols = {
        name: value for name, value in classes.items() if getattr(value, "_is_protocol", False)
    }
    blocks = [
        GENERATED.rstrip(),
        "# Protocol implementations",
        "Generated structural matches for each exported protocol. Runtime conformance and the "
        "testing suites remain authoritative; this page is an onboarding index.",
    ]
    ignored = {"__init__", "__subclasshook__", "__class_getitem__", "__protocol_attrs__"}
    for name, protocol in sorted(protocols.items()):
        members = set(getattr(protocol, "__protocol_attrs__", set())) - ignored
        matches = [
            candidate
            for candidate, implementation in classes.items()
            if candidate != name
            and not getattr(implementation, "_is_protocol", False)
            and all(hasattr(implementation, member) for member in members)
        ]
        shipped = [match for match in matches if not match.startswith("tesserix_adk.testing")]
        fakes = [match for match in matches if match.startswith("tesserix_adk.testing")]
        required = ", ".join(f"`{member}`" for member in sorted(members)) or "None"
        shipped_text = ", ".join(f"`{match}`" for match in shipped) or "No exported match."
        fake_text = ", ".join(f"`{match}`" for match in fakes) or "No exported fake."
        blocks.extend(
            [
                f"## `{name}`",
                f"**Required members:** {required}",
                f"**Shipped implementations:** {shipped_text}",
                f"**Testing fakes:** {fake_text}",
            ]
        )
    return "\n\n".join(blocks) + "\n"


def _experimental_modules() -> tuple[ModuleType, ...]:
    package = tesserix_adk.experimental
    modules = [package]
    modules.extend(
        importlib.import_module(info.name)
        for info in pkgutil.walk_packages(package.__path__, f"{package.__name__}.")
        if not any(part.startswith("_") for part in info.name.split(".")[1:])
    )
    return tuple(modules)


def build_pages(modules: Sequence[ModuleType] | None = None) -> dict[str, str]:
    """Build deterministic reference pages without writing them.

    Args:
        modules: Modules to render. The declared public package surface is the default.

    Returns:
        Mapping from reference filename to complete generated Markdown.
    """
    surface, objects, selected = _objects(modules)
    matrix = _stability_matrix()
    symbols, recipes = _recipe_contract()
    records = {record.name: record for record in deprecations()}
    upstream = third_party_re_exports(selected)
    groups: dict[str, list[str]] = {}
    for name in surface:
        parts = name.split(".")
        group = parts[1] if len(parts) > 2 else "root"
        groups.setdefault(group, []).append(name)

    pages: dict[str, str] = {}
    for group, names in sorted(groups.items()):
        title = "Package root" if group == "root" else group.replace("_", " ").title()
        blocks = [GENERATED.rstrip(), f"# {title} API", "Generated from the typed public surface."]
        for name in sorted(names):
            blocks.append(
                _symbol_block(
                    name,
                    surface[name],
                    objects[name],
                    level=_stability(name, objects[name], matrix),
                    symbols=symbols,
                    recipes=recipes,
                    third_party=name in upstream,
                    records=records,
                ).rstrip()
            )
        pages[f"{group}.md"] = "\n\n".join(blocks) + "\n"

    if modules is None:
        experimental_surface, experimental_objects, _ = _objects(_experimental_modules())
        blocks = [
            GENERATED.rstrip(),
            "# Experimental API",
            '!!! danger "Experimental: no compatibility promise"\n'
            "    These names can change or disappear in any release.",
        ]
        for name, description in sorted(experimental_surface.items()):
            blocks.append(
                f"## `{name}`\n\n**Stability:** `experimental`\n\n"
                f"{_summary(experimental_objects[name])}\n\n```python\n{description}\n```"
            )
        pages["experimental.md"] = "\n\n".join(blocks) + "\n"

    pages["protocols.md"] = _protocol_page(objects)
    rows = [
        f"| [{filename.removesuffix('.md').replace('_', ' ').title()}]({filename}) | "
        f"{len(groups.get(filename.removesuffix('.md'), ())) or '—'} |"
        for filename in sorted(pages)
        if filename not in {"index.md", "protocols.md"}
    ]
    index = [
        GENERATED.rstrip(),
        "# Generated API reference",
        "This reference is generated from `__all__`, typed signatures, docstrings, stability "
        "policy, deprecation records, and the runnable-recipe manifest. Run "
        "`make api-reference` after an intentional public API change; CI rejects drift.",
        "See [stability](../stability.md), [deprecations](../deprecations.md), and "
        "[security policy](../threat-model.md) before adopting a provisional surface.",
        "| Package | Public names |\n| --- | ---: |\n" + "\n".join(rows),
        "[Protocol implementations and testing fakes](protocols.md)",
    ]
    pages["index.md"] = "\n\n".join(index) + "\n"
    return pages


def _write(pages: Mapping[str, str]) -> None:
    REFERENCE.mkdir(parents=True, exist_ok=True)
    for filename, content in pages.items():
        destination = REFERENCE / filename
        temporary = destination.with_suffix(".md.tmp")
        temporary.write_text(content, encoding="utf-8")
        temporary.replace(destination)
    for path in REFERENCE.glob("*.md"):
        if path.name not in pages and path.read_text(encoding="utf-8").startswith(GENERATED):
            path.unlink()


def _check(pages: Mapping[str, str]) -> bool:
    current = {path.name: path.read_text(encoding="utf-8") for path in REFERENCE.glob("*.md")}
    generated_current = {
        name: value for name, value in current.items() if value.startswith(GENERATED)
    }
    if generated_current == pages:
        return True
    for filename in sorted(set(generated_current) | set(pages)):
        if generated_current.get(filename) == pages.get(filename):
            continue
        before = generated_current.get(filename, "").splitlines()
        after = pages.get(filename, "").splitlines()
        diff = difflib.unified_diff(
            before, after, fromfile=filename, tofile=f"generated/{filename}"
        )
        sys.stderr.write("\n".join(diff) + "\n")
    sys.stderr.write("API reference is out of date; run `make api-reference`.\n")
    return False


def main(argv: list[str] | None = None) -> int:
    """Validate and check the generated reference, or regenerate it with ``--write``.

    Args:
        argv: Optional command-line arguments.

    Returns:
        Zero when validation and drift checks pass; one otherwise.
    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="regenerate reference pages")
    args = parser.parse_args(argv)
    try:
        validate()
        pages = build_pages()
    except (ReferenceError, KeyError, ValueError) as failure:
        sys.stderr.write(f"API reference refused: {failure}\n")
        return 1
    if args.write:
        _write(pages)
        return 0
    return 0 if _check(pages) else 1


if __name__ == "__main__":
    raise SystemExit(main())
